// Turns data/checklists.json and data/import-*.json into the seed migrations (D1 in migrations/, PostgreSQL in migrations-pg/).
//   node scripts/build-sql.mjs
// Re-scores every imported audit with public/rules.js and prints it next to the total printed in the report,
// so any disagreement is visible before anything reaches the database.
// Once a migration has run in production, never regenerate it: add a new one.
import { readFileSync, writeFileSync } from 'node:fs';
import * as R from '../public/rules.js';

const root = new URL('..', import.meta.url);
const read = (p) => JSON.parse(readFileSync(new URL(p, root), 'utf8'));
const q = (v) => (v == null ? 'NULL' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const insert = (table, row) => `INSERT INTO ${table} (${Object.keys(row).join(', ')}) VALUES (${Object.values(row).map(q).join(', ')});`;

// ---------------------------------------------------------------- checklists
const checklists = read('data/checklists.json');
const items = new Map(); // `${templateId}:${code}` -> item row
const tplSql = ['-- Generated by scripts/build-sql.mjs from data/checklists.json. The three Bookends checklists.'];
let itemId = 0;
for (const t of checklists) {
  tplSql.push(insert('templates', { id: t.id, domain: t.domain, scheme: t.scheme, name: t.name, description: t.description, version: t.version, frequency_days: t.frequency_days, active: t.active }));
  t.items.forEach((it, i) => {
    itemId += 1;
    const row = {
      id: itemId, template_id: t.id, code: it.code, section: it.section, area: it.area, applies: it.applies || 'Both', text: it.text,
      guidance: it.guidance, critical: it.critical ? 1 : 0, criticality: it.criticality || null, weight: it.weight, kind: it.kind, sort: i + 1,
    };
    items.set(`${t.id}:${it.code}`, row);
    tplSql.push(insert('template_items', row));
  });
}
for (const dir of ['migrations', 'migrations-pg']) writeFileSync(new URL(`${dir}/0002_checklists.sql`, root), tplSql.join('\n') + '\n');

// ---------------------------------------------------------------- audit import
const data = read('data/import-2026-09.json');
const out = [`-- Generated by scripts/build-sql.mjs from data/import-2026-09.json: ${data.audits.length} audits by Vishal Patel, Aug–Sep 2026.`];
const siteId = new Map();
data.sites.forEach((s, i) => {
  siteId.set(s.key, i + 1);
  out.push(insert('sites', { id: i + 1, key: s.key, name: s.name, brand: s.brand, area: s.area, city: s.city, kind: s.kind }));
});

// Only the newest audit per unit and domain becomes the open fix list; older audits are history.
const latest = new Map();
for (const a of data.audits) {
  const k = `${a.site}:${a.domain}`;
  if (!latest.has(k) || latest.get(k).date <= a.date) latest.set(k, a);
}

let findingCount = 0;
const report = [];
data.audits.forEach((a, n) => {
  const auditId = n + 1;
  const tplItems = checklists.find((t) => t.id === a.template);
  const rows = a.responses.map((r) => {
    const it = items.get(`${a.template}:${r.code}`);
    if (!it) throw new Error(`Unknown item ${r.code} in template ${a.template} (${a.source_ref})`);
    return { it, r };
  });
  const scored = R.scoreAudit(rows.map(({ it }) => ({ id: it.id, section: it.section, weight: it.weight, critical: it.critical })),
    Object.fromEntries(rows.map(({ it, r }) => [it.id, r.result])));
  report.push({ unit: a.site, domain: a.domain, visit: a.visit, date: a.date, calc: `${R.fmtNum(scored.earned)}/${R.fmtNum(scored.possible)} = ${R.fmtPct(scored.score)}`,
    printed: `${R.fmtNum(a.reported.obtained)}/${R.fmtNum(a.reported.available)} = ${R.fmtPct(a.reported.pct)}`,
    match: Math.abs(scored.earned - a.reported.obtained) < 0.01 && Math.abs(scored.possible - a.reported.available) < 0.01 ? 'yes' : 'NO', flag: a.flag ? 'flagged' : '' });
  out.push(insert('audits', {
    id: auditId, site_id: siteId.get(a.site), template_id: a.template, domain: a.domain, audit_date: a.date, auditor: a.auditor,
    prepared_by: a.prepared_by, audit_type: a.audit_type, time_range: a.time_range, score: scored.score, earned: scored.earned,
    possible: scored.possible, band: scored.band, summary: a.summary, source: 'import', source_ref: a.source_ref, flag: a.flag,
    created_by: 'import', created_at: `${a.date} 12:00:00`,
  }));
  for (const { it, r } of rows) {
    out.push(insert('audit_responses', {
      audit_id: auditId, item_id: it.id, result: r.result, points: r.result === 'na' ? null : it.weight * R.POINTS[r.result],
      note: r.note, photos: r.photos.length ? JSON.stringify(r.photos) : null,
    }));
  }
  if (latest.get(`${a.site}:${a.domain}`) === a) {
    for (const { it, r } of rows) {
      const priority = R.priorityFor({ critical: !!it.critical, criticality: it.criticality }, r.result);
      if (!priority) continue;
      findingCount += 1;
      out.push(insert('findings', {
        site_id: siteId.get(a.site), audit_id: auditId, item_id: it.id, domain: a.domain, title: it.text, detail: r.note, priority,
        rating: r.result, marks: it.weight - it.weight * R.POINTS[r.result], kind: it.kind, status: 'open',
        due_date: R.addDays(data.import_date, R.PRIORITY[priority].fixDays),
        photos: r.photos.length ? JSON.stringify(r.photos) : null, created_at: `${a.date} 12:00:00`, updated_at: `${a.date} 12:00:00`,
      }));
    }
  }
  out.push(insert('activity', {
    at: `${a.date} 12:00:00`, actor: a.auditor, site_id: siteId.get(a.site), entity: 'audit', entity_id: auditId, action: 'imported',
    detail: `${R.DOMAINS[a.domain].label} visit ${a.visit}: ${R.fmtPct(scored.score)}, ${R.bandLabel(scored.band)}`,
  }));
});
for (const dir of ['migrations', 'migrations-pg']) writeFileSync(new URL(`${dir}/0003_import_2026_09.sql`, root), out.join('\n') + '\n');
console.table(report);
console.log(`${checklists.map((t) => `${t.scheme}: ${t.items.length} items`).join(' · ')} · ${data.sites.length} units · ${data.audits.length} audits · ${findingCount} open fixes`);
