-- Bookends compliance: PostgreSQL schema. The same tables as the D1 migrations 0001 and 0004–0009, in their final shape.
-- Dates are ISO 'YYYY-MM-DD' (local business date); timestamps are UTC 'YYYY-MM-DD HH:MM:SS' text, exactly as on D1,
-- so the app and rules.js read them unchanged. Flags (active, critical, …) stay 0/1 integers for the same reason.

-- UTC 'YYYY-MM-DD HH:MM:SS', the format SQLite's datetime('now') gave.
CREATE FUNCTION utc_now() RETURNS text LANGUAGE sql STABLE AS $$ SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') $$;

CREATE TABLE sites (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key           text UNIQUE,                          -- stable slug used by imports
  name          text    NOT NULL,
  brand         text,
  area          text,
  city          text,
  kind          text    NOT NULL DEFAULT 'restaurant', -- restaurant | kitchen
  manager       text,
  manager_phone text,
  active        integer NOT NULL DEFAULT 1,
  created_at    text    NOT NULL DEFAULT utc_now()
);

-- A checklist. Items are never edited in place: a changed checklist is a new template.
CREATE TABLE templates (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain         text    NOT NULL CHECK (domain IN ('food', 'maintenance')),
  scheme         text    NOT NULL,                     -- fssai1 | fssai2 | docket (rating labels, see rules.js)
  name           text    NOT NULL,
  description    text,
  version        integer NOT NULL DEFAULT 1,
  frequency_days integer NOT NULL DEFAULT 30,
  active         integer NOT NULL DEFAULT 1
);

CREATE TABLE template_items (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id integer NOT NULL REFERENCES templates(id),
  code        text    NOT NULL,                        -- L16 (ref 16) · K19 · M35
  section     text    NOT NULL,
  area        text,
  applies     text    NOT NULL DEFAULT 'Both',         -- Restaurant | CPK | Both
  text        text    NOT NULL,
  guidance    text,                                    -- "How to verify"
  critical    integer NOT NULL DEFAULT 0,              -- ★
  criticality text,                                    -- maintenance docket: Critical | High | Medium | Low
  weight      double precision NOT NULL,               -- marks for full compliance
  kind        text    NOT NULL DEFAULT 'physical',     -- paperwork | physical
  sort        integer NOT NULL
);
CREATE INDEX idx_items_template ON template_items(template_id, sort);

CREATE TABLE audits (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id      integer NOT NULL REFERENCES sites(id),
  template_id  integer NOT NULL REFERENCES templates(id),
  domain       text    NOT NULL CHECK (domain IN ('food', 'maintenance')),
  audit_date   text    NOT NULL,
  auditor      text,
  prepared_by  text,
  audit_type   text,
  time_range   text,
  score        double precision,                       -- 0..100, one decimal
  earned       double precision,
  possible     double precision,
  band         text CHECK (band IN ('exemplar', 'satisfactory', 'improve', 'noncompliance')),
  summary      text,
  source       text    NOT NULL DEFAULT 'app',         -- app | import
  source_ref   text,                                   -- original file name for imports
  flag         text,                                   -- data-quality note for the Compliance Head to confirm
  created_by   text,
  created_at   text    NOT NULL DEFAULT utc_now(),
  started_at   text,                                   -- UTC 'YYYY-MM-DDTHH:MM:SSZ', when the auditor began (app audits only)
  finished_at  text,                                   -- when it was submitted
  client_id    text                                    -- id made on the phone, so a resent audit is not saved twice
);
CREATE INDEX idx_audits_site ON audits(site_id, domain, audit_date);
CREATE UNIQUE INDEX audits_client_id ON audits (client_id) WHERE client_id IS NOT NULL;

CREATE TABLE audit_responses (
  audit_id integer NOT NULL REFERENCES audits(id) ON DELETE CASCADE,
  item_id  integer NOT NULL REFERENCES template_items(id),
  result   text    NOT NULL CHECK (result IN ('pass', 'partial', 'fail', 'na')),
  points   double precision,
  note     text,
  photos   text,                                       -- JSON array of storage keys
  PRIMARY KEY (audit_id, item_id)
);

-- A gap to close: from a Minor/Major/Observation/NC rating, with its corrective action (CAPA).
CREATE TABLE findings (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id      integer NOT NULL REFERENCES sites(id),
  audit_id     integer REFERENCES audits(id),
  item_id      integer REFERENCES template_items(id),
  domain       text    NOT NULL CHECK (domain IN ('food', 'maintenance')),
  title        text    NOT NULL,
  detail       text,
  priority     text    NOT NULL CHECK (priority IN ('critical', 'major', 'minor')),
  rating       text    NOT NULL DEFAULT 'fail' CHECK (rating IN ('fail', 'partial')),
  marks        double precision NOT NULL DEFAULT 0,    -- marks recovered when closed
  kind         text    NOT NULL DEFAULT 'physical',
  status       text    NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'fixed', 'closed')),
  owner        text,
  due_date     text    NOT NULL,
  root_cause   text,
  action_taken text,
  photos       text,                                   -- JSON: what the auditor saw
  evidence_key text,                                   -- proof of the fix
  is_repeat    integer NOT NULL DEFAULT 0,
  created_at   text    NOT NULL DEFAULT utc_now(),
  updated_at   text    NOT NULL DEFAULT utc_now(),
  fixed_at     text,
  closed_at    text,
  closed_by    text,
  close_note   text
);
CREATE INDEX idx_findings_status ON findings(status, site_id);
CREATE INDEX idx_findings_item ON findings(site_id, item_id, status);

CREATE TABLE licences (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id    integer NOT NULL REFERENCES sites(id),
  type       text    NOT NULL,
  number     text,
  authority  text,
  issued_on  text,
  expires_on text,
  severity   text    NOT NULL DEFAULT 'major' CHECK (severity IN ('critical', 'major', 'minor')),
  file_key   text,
  notes      text,
  updated_at text    NOT NULL DEFAULT utc_now()
);
CREATE INDEX idx_licences_site ON licences(site_id, expires_on);

-- Who did what, when. Append-only.
CREATE TABLE activity (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at        text    NOT NULL DEFAULT utc_now(),
  actor     text,
  site_id   integer,
  entity    text    NOT NULL,
  entity_id integer,
  action    text    NOT NULL,
  detail    text
);
CREATE INDEX idx_activity_at ON activity(at);

-- Personal accounts. Passwords are kept only as 'pbkdf2$<iterations>$<salt>$<hash>' (PBKDF2-SHA256, base64url).
CREATE TABLE users (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      text    NOT NULL,                       -- what they type to sign in, stored lower-case
  name          text    NOT NULL,
  role          text    NOT NULL DEFAULT 'manager',     -- head | manager
  site_id       integer REFERENCES sites(id),           -- the unit a manager looks after (NULL for a Compliance Head)
  password_hash text    NOT NULL,
  must_change   integer NOT NULL DEFAULT 0,             -- 1 = asked to choose a new password at next sign-in
  active        integer NOT NULL DEFAULT 1,
  created_at    text    NOT NULL DEFAULT utc_now(),
  created_by    text,
  last_login_at text
);
CREATE UNIQUE INDEX users_username ON users (lower(username));

-- Alerts a person has marked done, so they stop showing in that person's bell.
CREATE TABLE alert_dismissals (
  user_key  text NOT NULL,   -- 'u:<user id>', or 'n:<name>' for a team-code session
  alert_key text NOT NULL,
  at        text NOT NULL DEFAULT utc_now(),
  PRIMARY KEY (user_key, alert_key)
);
